export const GlobalMapping = {'modules':[{ value: '1', label: 'Wedding Planner', 'urlParam': 'wedding-planner' },
									    //{ value: '2', label: 'Wedding Venue', 'urlParam': 'wedding-venue' },
				 						//{ value: '3', label: 'Corporate Event Planner', 'urlParam': 'corporate-event-planner' },
										//{ value: '4', label: 'Corporate Event Venue', 'urlParam': 'corporate-event-venue' }
										],
					  		  'location': [{ value: '1', label: 'San Francisco / Bay Area', 'marketCity': 'san-francisco', 'marketCountry': 'US' },
										   { value: '2', label: 'New York', 'marketCity': 'new-york', 'marketCountry': 'US' },
										   { value: '3', label: 'Los Angeles', 'marketCity': 'los-angeles', 'marketCountry': 'US' },
										   { value: '4', label: 'Mumbai', 'marketCity': 'mumbai', 'marketCountry': 'IN' }],
							  'marketCity': [{label: 'San Francisco / Bay Area', 'value': 'san-francisco', 'marketCountry': 'US' },
										   {label: 'New York', 'value': 'new-york', 'marketCountry': 'US' },
										   {label: 'Los Angeles', 'value': 'los-angeles', 'marketCountry': 'US' },
										   {label: 'Mumbai', 'value': 'mumbai', 'marketCountry': 'IN' }],
							  'priceRange': [{label: '$', 'value': '1' },
							  				 {label: '$$', 'value': '2' },
							  				 {label: '$$$', 'value': '3' },
							  				 {label: '$$$$', 'value': '4' },
							  				 {label: '$$$$$', 'value': '5' }],
							  'listingEntity': [{label: 'Planner', value: '1', name: 'planner', 'logo': 'site-assets/images/icons/planner.svg' },
							  				    {label: 'Venue', value: '2', name: 'venue', 'logo': 'site-assets/images/icons/venue.svg' },
							  				    {label: 'Photographers', value: '3', name: 'photographer', 'logo': 'site-assets/images/icons/photographer.svg' },
							  				    {label: 'Catering', value: '4', name: 'catering', 'logo': 'site-assets/images/icons/catering.svg' },
							  				    {label: 'Hair & Makeup', value: '5', name: 'makeup', 'logo': 'site-assets/images/icons/makeup.svg' }]
					  		  
					  		  }