#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "Please provide env"
    exit
fi

# frontend app
cd /usr/share/app/aavoni/web-app
mv src/Config-$1.js src/Config.js
rm -rf node_modules/*
rm -rf node_modules/.bin/*
rm -rf node_modules/.cache/*
rm -f package-lock.json
cd /usr/share/app/aavoni/web-app
git pull
npm install
cd /usr/share/app/aavoni/web-app
npm run bundle

